### ISSUE TITLE
i can not connect essbase, where is the problem?

### ISSUE THREAD

**Issue by heezhou** [bcolas/PDIEssbasePlugin#1]
Unable to connect to the Essbase server: 
Unexpected error while connecting to the Essbase server: 无法连接到提供程序服务器。确保登录参数正确无误，而且提供程序服务器已经启动。
无法连接到提供程序服务器。确保登录参数正确无误，而且提供程序服务器已经启动。

org.pentaho.di.core.exception.KettleException: 
Unexpected error while connecting to the Essbase server: 无法连接到提供程序服务器。确保登录参数正确无误，而且提供程序服务器已经启动。
无法连接到提供程序服务器。确保登录参数正确无误，而且提供程序服务器已经启动。

	at org.pentaho.di.essbase.core.EssbaseHelper.connect(EssbaseHelper.java:156)
	at org.pentaho.di.essbase.core.EssbaseHelper.getConnectionTestReport(EssbaseHelper.java:105)
	at org.pentaho.di.core.database.DatabaseMeta.testConnection(DatabaseMeta.java:2795)
	at org.pentaho.ui.database.event.DataHandler.testDatabaseConnection(DataHandler.java:598)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:313)
	at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:157)
	at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:141)
	at org.pentaho.ui.xul.swt.tags.SwtButton.access$500(SwtButton.java:43)
	at org.pentaho.ui.xul.swt.tags.SwtButton$4.widgetSelected(SwtButton.java:137)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:820)
	at org.eclipse.jface.window.Window.open(Window.java:796)
	at org.pentaho.di.ui.xul.KettleDialog.show(KettleDialog.java:80)
	at org.pentaho.di.ui.xul.KettleDialog.show(KettleDialog.java:47)
	at org.pentaho.di.ui.core.database.dialog.XulDatabaseDialog.open(XulDatabaseDialog.java:116)
	at org.pentaho.di.ui.core.database.dialog.DatabaseDialog.open(DatabaseDialog.java:60)
	at org.pentaho.di.ui.spoon.delegates.SpoonDBDelegate.newConnection(SpoonDBDelegate.java:475)
	at org.pentaho.di.ui.spoon.delegates.SpoonDBDelegate.newConnection(SpoonDBDelegate.java:462)
	at org.pentaho.di.ui.spoon.Spoon.newConnection(Spoon.java:8811)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:313)
	at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:157)
	at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:141)
	at org.pentaho.ui.xul.jface.tags.JfaceMenuitem.access$100(JfaceMenuitem.java:43)
	at org.pentaho.ui.xul.jface.tags.JfaceMenuitem$1.run(JfaceMenuitem.java:106)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:545)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:490)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:402)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1359)
	at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:7990)
	at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9290)
	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:685)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
Caused by: com.essbase.api.base.EssException: 无法连接到提供程序服务器。确保登录参数正确无误，而且提供程序服务器已经启动。
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.openConnection(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.invokeMethod(Unknown Source)
	at com.essbase.api.session.EssOrbPluginHttp.invokeMethod(Unknown Source)
	at com.essbase.api.session.EssOrbPlugin.signOn(Unknown Source)
	at com.essbase.api.session.Essbase.signOn(Unknown Source)
	at com.essbase.api.session.Essbase.signOn_internal(Unknown Source)
	at com.essbase.api.session.Essbase.signOn(Unknown Source)
	at org.pentaho.di.essbase.core.EssbaseHelper.connect(EssbaseHelper.java:141)
	... 54 more

===============================================
and  i can connect essbase by tableua .
i want to know  what information should be included in the  'database name ' cloumn?  
my essbase application named 'MinthBOM' ,and under this  have a database named 'BOM'，whether  i write 'MinthBOM' or  write 'BOM'  ,i can not  connect essbase;
i use  pdi 6.1;

**Comment by heezhou** [comment]
if any news, email:
jian.he@minthgroup.com

**Comment by bcolas** [comment]
Please find attached to this email a screen capture of what should be put in database name property of Essbase connection. I agree the field is improperly named.

![pdi_essbase_db_setup](https://cloud.githubusercontent.com/assets/8590669/24093610/fdec7a0a-0d54-11e7-9bcd-f184904ccbf4.png)
